"""User migration

Revision ID: 124db5c896e0
Revises: 268038be3920
Create Date: 2024-04-07 17:18:44.734459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '124db5c896e0'
down_revision = '268038be3920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('prod_article', sa.String(length=50), nullable=False),
    sa.Column('prod_name', sa.String(length=100), nullable=True),
    sa.Column('prod_category', sa.String(length=100), nullable=True),
    sa.Column('prod_description', sa.String(length=200), nullable=True),
    sa.Column('in_stock', sa.Boolean(), nullable=True),
    sa.Column('prod_price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('prod_article')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_surname', sa.String(length=50), nullable=True),
    sa.Column('user_name', sa.String(length=50), nullable=True),
    sa.Column('user_gender', sa.Boolean(), nullable=True),
    sa.Column('user_email', sa.String(length=50), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_user_name'), ['user_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_user_name'))

    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('products')
    # ### end Alembic commands ###
