"""empty message

Revision ID: 20445b180d7b
Revises: c2c86e5e1860
Create Date: 2024-05-24 11:23:39.509146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20445b180d7b'
down_revision = 'c2c86e5e1860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sizes_in_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prod_id', sa.String(length=50), nullable=True),
    sa.Column('size', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['prod_id'], ['products.prod_article'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.Numeric(), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('size', sa.Numeric(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('size')

    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.drop_column('size')

    op.drop_table('sizes_in_stock')
    # ### end Alembic commands ###
