"""empty message

Revision ID: 418559ed64b9
Revises: 628d80afcfe8
Create Date: 2024-05-22 15:37:14.612437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '418559ed64b9'
down_revision = '628d80afcfe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cat_name', sa.String(length=50), nullable=True),
    sa.Column('cat_photo', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cat_name')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cat_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'categories', ['cat_id'], ['id'])
        batch_op.drop_column('prod_category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prod_category', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cat_id')

    op.drop_table('categories')
    # ### end Alembic commands ###
