"""empty message

Revision ID: 628d80afcfe8
Revises: 8d32fc83d1b9
Create Date: 2024-05-22 15:19:10.090885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '628d80afcfe8'
down_revision = '8d32fc83d1b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('prod_old_price',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Numeric(),
               existing_nullable=True)
        batch_op.alter_column('prod_price',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Numeric(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('prod_price',
               existing_type=sa.Numeric(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
        batch_op.alter_column('prod_old_price',
               existing_type=sa.Numeric(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)

    # ### end Alembic commands ###
