"""second migrate

Revision ID: 67587a62356e
Revises: 
Create Date: 2024-03-16 22:01:04.951358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67587a62356e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_user_name'), ['user_name'], unique=False)
        batch_op.create_unique_constraint(None, ['user_email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_users_user_name'))

    # ### end Alembic commands ###
