"""empty message

Revision ID: f21ad9c753ca
Revises: 7562d5902fec
Create Date: 2024-05-22 14:01:22.809398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f21ad9c753ca'
down_revision = '7562d5902fec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('in_carousel', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('best_prod', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('best_prod')
        batch_op.drop_column('in_carousel')

    # ### end Alembic commands ###
